### ISSUE TITLE
Backport for previous SW versions

### ISSUE THREAD

**Issue by jsculley** [jsculley/AutoGetReferencedAddin#2]
Should create branches for other SW releases with appropriate COM references and object versions so the add-in can be used in earlier SW versions

**Comment by jsculley** [comment]
Thinking about this further, branches are not the way to do this.  Instead I'll create a pair of projects (add-in and installer) in the solution for each SW version.  This will require renaming the existing projects to add **-2022** at the end.  The projects will each reference the appropriate library versions and use only types available in those libraries.

**Comment by nemecben** [comment]
Are there features in the API of newer version that merit the use of the newest interfaces for this add-in?  What would happen if it's just left using interfaces compatible with older version?  Obviously, would only go back so far and as time passes the oldest supported version would be increased.

**Comment by jsculley** [comment]
Newer SW versions **should** be able to use older interface declarations in the code.  With each SW release there may be some interfaces that are obsoleted.  Sometimes they keep working in later versions, and sometimes they stop working.  I have had one instance where the **new** interface was broken and I had to use the older version.

My typical approach is to go through the release notes and update all my projects with the latest interfaces as part of testing the new release of SW.  Its a pretty straight forward search/replace operation.  While I may not be using any of the new functionality in the interface, keeping the declarations up to date  seems like a good idea.

If separate projects are created for each SW version, there may be a bit of extra work making sure changes are made in each project but the referenced library management will be a lot easier.

**Comment by jsculley** [comment]
@nemecben 

I've created a 2019 project but before I can check it in I need copies of the Interop libraries to include in the project.

![image](https://user-images.githubusercontent.com/8567569/175663900-9f4b15cd-5287-40b2-9b95-47f980a4b23e.png)

Copies from the **C:\Program Files\SolidWorks Corp\SOLIDWORKS\api\redist** preferred.  The EPDM library and tools libraries come from **C:\Program Files\SolidWorks Corp\SOLIDWORKS** and **C:\Program Files\SolidWorks Corp\SOLIDWORKS PDM**

**Comment by nemecben** [comment]
[SW-PDM_2019_InteropLibraries.zip](https://github.com/jsculley/AutoGetReferencedAddin/files/8981607/SW-PDM_2019_InteropLibraries.zip)

Zip file attached with the five libraries from the locations you specified.

**Comment by jsculley** [comment]
The 'develop' branch has been restructured with SW2022 and SW2019 specific projects.  I don't have SW 2019 here, so please clone the repo, build and report any problems.

**Comment by nemecben** [comment]
Cloned and here is what I found:

- Debugger breaks at line 311 for a few objects like Cut_List_Items and Sheets.  The GetObject() throws "The supplied object ID is not valid" exception.  I'm struggling to figure out what's going on because those are indeed EdmObject_File types according to the selection.MeType, the data in Documents table confirm that when I query by that docID.   Since we're not getting these "files" twe can just skip these in the IEdmSelectionList.  I made a quick fix of wrapping in try&catch then if the exception is of that type continue else throw the exception again.  I was taught to use conditionals rather than letting exceptions be thrown for flow control.  The only test I can think of is checking for expected file types in the path which seems a bit hack as well.  I don't konw.

![image](https://user-images.githubusercontent.com/25161718/176008404-bffc26ab-f083-44bd-9bd5-42f59c96ac59.png)


-  `int localVersion = retrievedFile.GetLocalVersionNo2(selection.mbsPath, out bool obsolete);`   Is throwing a 'The file could not be found.' exception on virtual components.  the selection.mbsPath is showing the file in the vault folder of the parent assembly.  I'm guessing the file is not found because it's not actually there?  If I understand correctly the virtual component file is "embedded" in the assembly file so it's really not any concern to us.  It would be nice to also filter these out of the selection set as well.  I don't see any way to set up the SelectionList to ignore object types or how to test each one.  In the database Documents table the virtual components have ObjectTypeID = 2.

![image](https://user-images.githubusercontent.com/25161718/176028473-b605eb5e-615b-4beb-81df-850e6356ea54.png)

**Comment by jsculley** [comment]
I will run some tests with SW2022 to make sure the problem is version specific.  My testing was minimal so Cut List items and Virtual parts were not included.  I recall having issues with those before in other PDM add-ins.  I'll look at how I handled them there.

**Comment by jsculley** [comment]
Reproduced with SW2022.  I've added #4 to track this.

**Comment by jsculley** [comment]
Latest commit includes the fix, which is (as you've found) to wrap with try-catch and swallow the Exception.  This is the approach used in my other add-ins.

**Comment by jsculley** [comment]
Since the backport to 2019 is functional from a build standpoint, I'm going to close this issue.  Open a new issue for any new items you find or requests for functionality.  I'm basically using the [Git-Flow](https://nvie.com/posts/a-successful-git-branching-model/) development process.   Having an issue for each item/feature makes the process much smoother.
